create table ARUN_EMPLOYEES(ID INT PRIMARY KEY,FIRST_NAME VARCHAR(40),LAST_NAME VARCHAR(40),SALARY DECIMAL(8,2),DEPARTMENT_ID INT,YEAR_OF_JOINING DATETIME,YEAR_OF_RELIVING DATETIME)
CREATE TABLE ARUN_DEPARTMENTS(DEPARTMENT_ID INT PRIMARY KEY,MANAGER_ID INT,DEPARTMENT_NAME VARCHAR(50))
insert into ARUN_EMPLOYEES values(108,'sarA','KAVI',17000,22,'2022-09-10','2023-05-2')
select * from ARUN_EMPLOYEES where FIRST_NAME like 's%n'
insert into ARUN_DEPARTMENTS values(100,77,'physics')
select * from ARUN_EMPLOYEES where DEPARTMENT_ID =19 AND FIRST_NAME like 's%'
select * from ARUN_EMPLOYEES
select * from ARUN_DEPARTMENTS
SELECT * FROM ARUN_EMPLOYEES where SALARY BETWEEN 16000 AND 17000
select * from ARUN_EMPLOYEES where DEPARTMENT_ID like '_2%'
select * from ARUN_EMPLOYEES where DEPARTMENT_ID in (19,12,17)
select FIRST_NAME,SALARY,ARUN_EMPLOYEES.DEPARTMENT_ID from ARUN_EMPLOYEES inner join ARUN_DEPARTMENTS on ARUN_EMPLOYEES.ID=ARUN_DEPARTMENTS.DEPARTMENT_ID where MANAGER_ID IS  NULL
select * from ARUN_EMPLOYEES ORDER BY FIRST_NAME
select FIRST_NAME,DEPARTMENT_ID,SALARY FROM ARUN_EMPLOYEES ORDER BY DEPARTMENT_ID,SALARY DESC
select LEFT(FIRST_NAME,3) from ARUN_EMPLOYEES
select RIGHT(LAST_NAME,2) from ARUN_EMPLOYEES
select AVG(SALARY) AS AVGRGESALARY FROM ARUN_EMPLOYEES WHERE DEPARTMENT_ID =19 
SELECT MAX(SALARY) AS MAXIMUM FROM ARUN_EMPLOYEES;
SELECT FIRST_NAME,CHARINDEX('a',FIRST_NAME) AS POSITION FROM ARUN_EMPLOYEES
select FIRST_NAME,YEAR(YEAR_OF_JOINING) from ARUN_EMPLOYEES where DEPARTMENT_ID=17
select LAST_NAME from ARUN_EMPLOYEES where YEAR_OF_JOINING BETWEEN '2000-09-10' and '2024-05-2'
select YEAR(YEAR_OF_JOINING) FROM ARUN_EMPLOYEES GROUP BY YEAR(YEAR_OF_JOINING)  HAVING COUNT(ID)>1
SELECT ID, AVG(SALARY) AS AVGSALARY FROM ARUN_EMPLOYEES GROUP BY ID HAVING AVG(SALARY)>16000
SELECT * FROM ARUN_EMPLOYEES WHERE YEAR(YEAR_OF_JOINING)=2022
SELECT ID,DATEDIFF(DAY,YEAR_OF_JOINING,YEAR_OF_RELIVING) AS DATE FROM ARUN_EMPLOYEES
SELECT UPPER(FIRST_NAME)AS FIRSTNAME,LOWER(LAST_NAME) AS LASTNAME FROM ARUN_EMPLOYEES
SELECT LEN(FIRST_NAME),LAST_NAME FROM ARUN_EMPLOYEES WHERE LAST_NAME LIKE '_a%'
SELECT FIRST_NAME ,DATEDIFF(YEAR,YEAR_OF_JOINING,YEAR_OF_RELIVING) AS EXPERI FROM ARUN_EMPLOYEES
SELECT * FROM ARUN_EMPLOYEES WHERE (MONTH(YEAR_OF_JOINING))=5
SELECT ID,FIRST_NAME,LAST_NAME  FROM ARUN_EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY)  FROM ARUN_EMPLOYEES) 
UPDATE ARUN_EMPLOYEES SET FIRST_NAME='JOY' WHERE ID=107
CREATE TABLE ARUNKU_EMPLOYEES(DEPARTMENTID INT FOREIGN KEY REFERENCES ARUN_EMPLOYEES(ID),EMPLOYEENAME VARCHAR(30),DEPARTMENT VARCHAR(35))
SELECT * FROM ARUNKU_EMPLOYEES
SELECT * FROM ARUN_EMPLOYEES
INSERT INTO ARUNKU_EMPLOYEES VALUES(110,'goo','hello')
CREATE VIEW ARUN_VIEW AS SELECT ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID FROM [ARUN_EMPLOYEES] 
SELECT ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID FROM ARUN_VIEW
CREATE SYNONYM ARUNK_EMPLOYEES FOR ARUN_EMPLOYEES
SELECT * FROM ARUNK_EMPLOYEES
create procedure ARUN_D as select*from ARUN_EMPLOYEES where YEAR_OF_JOINING between '2010-10-01 01:30:00.000 ' and '2023-10-21 01:30:00.000 '
exec ARUN_D
create procedure ARUN_VAL as insert into ARUN_DEPARTMENTS values (35,119,'Technical')
exec ARUN_VAL
select replace(convert(varchar, '2006-12-30',101),'-','') + replace(convert(varchar, '00:38:54',108),':','');
select avg(SALARY) as 'AVERAGE SALARY' from ARUN_EMPLOYEES where YEAR_OF_JOINING < 2023
select month (YEAR_OF_JOINING) as MONTH_OF_JOINING from ARUN_EMPLOYEES  group by month (YEAR_OF_JOINING) having count(ID)>5
