create table ARUN_EMPLOYEES(ID INT PRIMARY KEY,FIRST_NAME VARCHAR(40),LAST_NAME VARCHAR(40),SALARY DECIMAL(8,2),DEPARTMENT_ID INT,YEAR_OF_JOINING DATETIME,YEAR_OF_RELIVING DATETIME)
CREATE TABLE ARUN_DEPARTMENTS(DEPARTMENT_ID INT PRIMARY KEY,MANAGER_ID INT,DEPARTMENT_NAME VARCHAR(50))
insert into ARUN_EMPLOYEES values(108,'sarA','KAVI',17000,22,'2022-09-10','2023-05-2')
select * from ARUN_EMPLOYEES where FIRST_NAME like 's%n'
insert into ARUN_DEPARTMENTS values(100,77,'physics')
select * from ARUN_EMPLOYEES where DEPARTMENT_ID =19 AND FIRST_NAME like 's%'
select * from ARUN_EMPLOYEES
select * from ARUN_DEPARTMENTS
SELECT * FROM ARUN_EMPLOYEES where SALARY BETWEEN 16000 AND 17000
select * from ARUN_EMPLOYEES where DEPARTMENT_ID like '_2%'
select * from ARUN_EMPLOYEES where DEPARTMENT_ID in (19,12,17)
select FIRST_NAME,SALARY,ARUN_EMPLOYEES.DEPARTMENT_ID from ARUN_EMPLOYEES inner join ARUN_DEPARTMENTS on ARUN_EMPLOYEES.ID=ARUN_DEPARTMENTS.DEPARTMENT_ID where MANAGER_ID IS  NULL
select * from ARUN_EMPLOYEES ORDER BY FIRST_NAME
select FIRST_NAME,DEPARTMENT_ID,SALARY FROM ARUN_EMPLOYEES ORDER BY DEPARTMENT_ID,SALARY DESC
select LEFT(FIRST_NAME,3) from ARUN_EMPLOYEES
select RIGHT(LAST_NAME,2) from ARUN_EMPLOYEES
select AVG(SALARY) AS AVGRGESALARY FROM ARUN_EMPLOYEES WHERE DEPARTMENT_ID =19 
SELECT MAX(SALARY) AS MAXIMUM FROM ARUN_EMPLOYEES;
SELECT FIRST_NAME,CHARINDEX('a',FIRST_NAME) AS POSITION FROM ARUN_EMPLOYEES
